var = input('Digite Algo: ')
print('O tipo primitivo dessa variavel é', type(var))
print('Só tem espaços? ', var.isspace())
print('é um numero? ', var.isnumeric())
print('é alfabetico? ', var.isalpha())
print('é alfanumérico? ', var.isalnum())
print('esta em maiusculas', var.isupper())
print('esta em minusculas?', var.islower())
print('esta capitalizada?', var.istitle())
print('esta em ascii', var.isascii())